name: fitness_app
description: "AI-Powered Fitness & Nutrition Tracker with Dynamic Music Adjustment"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4

  provider: ^6.1.2
  google_sign_in: ^6.3.0

  http: ^1.3.0
  web_socket_channel: ^3.0.2

  camera: ^0.11.1
  image_picker: ^1.1.2
  google_mlkit_image_labeling: ^0.13.0
  google_generative_ai: ^0.4.6
  

  health: ^13.3.1
  sensors_plus: ^6.1.1
  pedometer: ^4.0.0
  geolocator: ^13.0.2
  location: ^7.0.1
  flutter_blue_plus: ^2.3.9
  maplibre_gl: ^0.26.2
  flutter_web_auth_2: ^5.0.0

  spotify_sdk: ^3.0.2

  fl_chart: ^0.70.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  permission_handler: ^11.4.0
  lottie: ^3.3.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  app_links: ^7.0.0
  crypto: ^3.0.6
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  workmanager: ^0.9.0

    
dev_dependencies:
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"   # your 1024×1024 image

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/models/
    - assets/exercises.json
