// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBND5cdDAG_P_59xniwbSOl8aurooGKrW8',
    appId: '1:200266998037:web:23020cb487bb642848c91c',
    messagingSenderId: '200266998037',
    projectId: 'track-497809',
    authDomain: 'track-497809.firebaseapp.com',
    storageBucket: 'track-497809.firebasestorage.app',
    measurementId: 'G-BDT5WXJ4CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn5b26QdHSjikjzH9IwZ6K238ey_oxFBY',
    appId: '1:200266998037:android:fd264a46e09c43ab48c91c',
    messagingSenderId: '200266998037',
    projectId: 'track-497809',
    storageBucket: 'track-497809.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVSSRhse0GIH7uNup5miqHQPAqgZzxO6Q',
    appId: '1:200266998037:ios:313e5fc233ffae8448c91c',
    messagingSenderId: '200266998037',
    projectId: 'track-497809',
    storageBucket: 'track-497809.firebasestorage.app',
    iosBundleId: 'com.fyp.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVSSRhse0GIH7uNup5miqHQPAqgZzxO6Q',
    appId: '1:200266998037:ios:313e5fc233ffae8448c91c',
    messagingSenderId: '200266998037',
    projectId: 'track-497809',
    storageBucket: 'track-497809.firebasestorage.app',
    iosBundleId: 'com.fyp.fitnessApp',
  );
}
