import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:intl/intl.dart';
import '../providers/auth_provider.dart';
import '../providers/workout_provider.dart';
import '../providers/nutrition_provider.dart';
import '../providers/sleep_provider.dart';
import '../providers/health_provider.dart';
import '../providers/motion_provider.dart';
import '../providers/place_provider.dart';
import '../providers/news_provider.dart';
import '../providers/planning_provider.dart';
import '../models/planning_model.dart';
import '../models/meal_model.dart';
import '../models/workout_model.dart';
import '../models/weight_entry_model.dart';
import '../config/theme.dart';
import '../services/firebase_service.dart';
import '../services/health_connect_service.dart';
import '../widgets/quick_tour.dart';
import '../widgets/news_carousel.dart';
import '../widgets/map_preview_card.dart';
import '../utils/shimmer.dart';
import 'workout_screen.dart';
import 'nutrition_screen.dart';
import 'profile_screen.dart';
import 'planning_screen.dart';
import 'body_statistics_screen.dart';
import 'run_tracking_screen.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  int _currentIndex = 0;

  late final List<Widget> _screens;
  late final List<QuickTourStep> _tourSteps;

  final _dashboardKey = GlobalKey();
  final _startWorkoutKey = GlobalKey();
  final _logMealKey = GlobalKey();
  final _musicFitKey = GlobalKey();
  final _heartRateKey = GlobalKey();
  final _aiChatKey = GlobalKey();
  final _bottomNavKey = GlobalKey();

  final _navPlanningKey = GlobalKey();
  final _navWorkoutKey = GlobalKey();
  final _navDietKey = GlobalKey();
  final _navProfileKey = GlobalKey();

  @override
  void initState() {
    super.initState();
    _tourSteps = _buildTourSteps();
    _screens = [
      _DashboardTab(
        dashboardKey: _dashboardKey,
        tourSteps: _tourSteps,
        aiChatKey: _aiChatKey,
      ),
      const _PlanningTab(),
      const _WorkoutTab(),
      const _NutritionTab(),
      const _ProfileTab(),
      const _StatisticsTab(),
    ];
  }

  List<QuickTourStep> _buildTourSteps() {
    return [
      QuickTourStep(
        targetKey: _startWorkoutKey,
        title: 'Start a Workout',
        description:
            'Tap here to begin tracking your exercise. Real-time heart rate and adaptive music will keep you motivated.',
        icon: Icons.fitness_center,
        onActionTap: () => Navigator.pushNamed(context, '/workout'),
      ),
      QuickTourStep(
        targetKey: _logMealKey,
        title: 'Log Your Meal',
        description:
            'Snap a photo of your food or enter calories manually. AI will recognize your meal and track nutrition.',
        icon: Icons.camera_alt,
        onActionTap: () => Navigator.pushNamed(context, '/food-capture'),
      ),
      QuickTourStep(
        targetKey: _musicFitKey,
        title: 'Music Fit',
        description:
            'Get smart music recommendations that match your workout intensity and heart rate zone.',
        icon: Icons.music_note,
        onActionTap: () =>
            Navigator.pushNamed(context, '/music-recommendations'),
      ),
      QuickTourStep(
        targetKey: _heartRateKey,
        title: 'Heart Rate Monitor',
        description:
            'Toggle heart rate monitoring on/off. Works with your smartwatch for real-time tracking.',
        icon: Icons.favorite,
      ),
      QuickTourStep(
        targetKey: _navPlanningKey,
        title: 'AI Planning',
        description:
            'Get personalized fitness plans generated by AI. Choose from multiple options based on your goals.',
        icon: Icons.auto_awesome,
        onActionTap: () => setState(() => _currentIndex = 1),
      ),
      QuickTourStep(
        targetKey: _navWorkoutKey,
        title: 'Workout Tracker',
        description:
            'Switch to the Workout tab to view detailed exercise metrics, heart rate charts, and start sessions.',
        icon: Icons.fitness_center,
        onActionTap: () => setState(() => _currentIndex = 2),
      ),
      QuickTourStep(
        targetKey: _navDietKey,
        title: 'Diet & Nutrition',
        description:
            'Track your daily calories, protein, carbs, and fat. Log meals manually or scan with your camera.',
        icon: Icons.restaurant,
        onActionTap: () => setState(() => _currentIndex = 3),
      ),
      QuickTourStep(
        targetKey: _navProfileKey,
        title: 'Your Profile',
        description:
            'Edit your fitness goals, connect Spotify and smartwatch, view body stats, and manage settings.',
        icon: Icons.person,
        onActionTap: () => setState(() => _currentIndex = 4),
      ),
      QuickTourStep(
        targetKey: _aiChatKey,
        title: 'AI Assistant',
        description:
            'Get personalized fitness advice, meal suggestions, and workout tips from your AI coach.',
        icon: Icons.auto_awesome,
        onActionTap: () => Navigator.pushNamed(context, '/ai-chat'),
      ),
    ];
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _screens[_currentIndex],
      bottomNavigationBar: Stack(
        key: _bottomNavKey,
        children: [
          BottomNavigationBar(
            currentIndex: _currentIndex,
            onTap: (i) => setState(() => _currentIndex = i),
            items: const [
              BottomNavigationBarItem(
                icon: Icon(Icons.dashboard),
                label: 'Home',
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.auto_awesome),
                label: 'Planning',
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.fitness_center),
                label: 'Workout',
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.restaurant),
                label: 'Diet',
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.person),
                label: 'Profile',
              ),
            ],
          ),
          _NavBarMarker(key: _navPlanningKey, index: 1, totalItems: 5),
          _NavBarMarker(key: _navWorkoutKey, index: 2, totalItems: 5),
          _NavBarMarker(key: _navDietKey, index: 3, totalItems: 5),
          _NavBarMarker(key: _navProfileKey, index: 4, totalItems: 5),
        ],
      ),
    );
  }
}

// ─── Helper widgets ─────────────────────────────────────────────

class _NavBarMarker extends StatelessWidget {
  final int index;
  final int totalItems;
  const _NavBarMarker({
    super.key,
    required this.index,
    required this.totalItems,
  });

  @override
  Widget build(BuildContext context) {
    return Positioned(
      left: MediaQuery.of(context).size.width / totalItems * index,
      width: MediaQuery.of(context).size.width / totalItems,
      top: 0,
      bottom: 0,
      child: const SizedBox.expand(),
    );
  }
}

class _StatisticsTab extends StatelessWidget {
  const _StatisticsTab();
  @override
  Widget build(BuildContext context) => const BodyStatisticsScreen();
}

class _PlanningTab extends StatelessWidget {
  const _PlanningTab();
  @override
  Widget build(BuildContext context) =>
      const PlanningScreen(showBottomNav: false);
}

class _WorkoutTab extends StatelessWidget {
  const _WorkoutTab();
  @override
  Widget build(BuildContext context) =>
      const WorkoutScreen(showBottomNav: false);
}

class _NutritionTab extends StatelessWidget {
  const _NutritionTab();
  @override
  Widget build(BuildContext context) => const NutritionScreen();
}

class _ProfileTab extends StatelessWidget {
  const _ProfileTab();
  @override
  Widget build(BuildContext context) =>
      const ProfileScreen(showBottomNav: false);
}

// ─── Dashboard Tab ──────────────────────────────────────────────

class _DashboardTab extends StatefulWidget {
  final GlobalKey? dashboardKey;
  final List<QuickTourStep> tourSteps;
  final GlobalKey aiChatKey;

  const _DashboardTab({
    this.dashboardKey,
    required this.tourSteps,
    required this.aiChatKey,
  });

  @override
  State<_DashboardTab> createState() => _DashboardTabState();
}

class _DashboardTabState extends State<_DashboardTab>
    with WidgetsBindingObserver {
  final _quickTourKey = GlobalKey<QuickTourState>();
  bool _showTourPrompt = false;
  bool _isDashboardLoading = true;
  List<Map<String, dynamic>> _calorieHistory = [];
  String _weightFilter = 'All';
  String _reportPeriod = 'This Week';
  List<WeightEntry> _weightHistory = [];
  List<Meal> _reportMeals = [];

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    WidgetsBinding.instance.addPostFrameCallback((_) => _loadData());
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  Future<void> _loadData() async {
    setState(() => _isDashboardLoading = true);
    final auth = context.read<AuthProvider>();
    if (auth.user == null) {
      setState(() => _isDashboardLoading = false);
      return;
    }

    try {
      final prefs = await SharedPreferences.getInstance();
      final localDone = prefs.getBool('quick_tour_done') ?? false;
      final userDone = auth.user?.hasSeenQuickTour ?? false;

      if (!userDone && !localDone) {
        if (!mounted) return;
        setState(() => _showTourPrompt = true);
        Future.delayed(const Duration(milliseconds: 600), () {
          _quickTourKey.currentState?.start();
        });
      } else if (!userDone) {
        final updated = auth.user!.copyWith(hasSeenQuickTour: true);
        await auth.updateProfile(updated);
      }

      final nutrition = context.read<NutritionProvider>();
      final health = context.read<HealthProvider>();
      final sleepProvider = context.read<SleepProvider>();
      final workoutProvider = context.read<WorkoutProvider>();
      final placeProvider = context.read<PlaceProvider>();
      final newsProvider = context.read<NewsProvider>();
      final planningProvider = context.read<PlanningProvider>();

      nutrition.initDailyCalorieGoal(auth.user!);

      await nutrition.calculateAndSetTDEE(
        user: auth.user!,
        activityLevel: auth.user!.activityLevel,
        onSave: (goal) async {
          final updated = auth.user!.copyWith(dailyCalorieTarget: goal);
          await auth.updateProfile(updated);
        },
      );

      await health.initializeHealthAccess();

      if (!mounted) return;

      await Future.wait([
        sleepProvider.loadSleepData(auth.user!.uid).catchError((e, s) => debugPrint('loadSleepData: $e')),
        nutrition.loadTodayMeals(auth.user!.uid).catchError((e, s) => debugPrint('loadTodayMeals: $e')),
        nutrition.loadWeeklyCalories(auth.user!.uid).catchError((e, s) => debugPrint('loadWeeklyCalories: $e')),
        nutrition.loadWeightHistory(auth.user!.uid).catchError((e, s) => debugPrint('loadWeightHistory: $e')),
        workoutProvider.loadDashboardData(auth.user!.uid).catchError((e, s) => debugPrint('loadDashboardData: $e')),
        placeProvider.loadPlaces(auth.user!.uid).catchError((e, s) => debugPrint('loadPlaces: $e')),
        newsProvider.fetchNews().catchError((e, s) => debugPrint('fetchNews: $e')),
        planningProvider.loadBookmarks(auth.user!.uid).catchError((e, s) => debugPrint('loadBookmarks: $e')),
      ]);

      _weightHistory = nutrition.weightHistory;

      final recentMeals = await nutrition.loadRecentMeals(auth.user!.uid, days: 30);
      _computeCalorieHistory(recentMeals, workoutProvider.workouts);
      await _loadReportMeals(nutrition, auth.user!.uid);

      if (!mounted) return;
      await _syncHealthConnectSteps(auth.user!.uid);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error loading data: $e')));
      }
    } finally {
      if (mounted) {
        setState(() {
          _isDashboardLoading = false;
        });
      }
    }
  }

  void _saveTodaySteps() {
    final uid = context.read<AuthProvider>().user?.uid;
    final steps = context.read<MotionProvider>().stepsToday;
    if (uid != null) {
      FirebaseService().saveDailySteps(uid, DateTime.now(), steps);
    }
  }

  Future<void> _syncHealthConnectSteps(String uid) async {
    try {
      final hc = HealthConnectService();
      if (!await hc.isAvailable) return;
      final steps = await hc.getStepsToday();
      if (steps > 0) {
        await FirebaseService().saveDailySteps(uid, DateTime.now(), steps);
      }
    } catch (e) {
      debugPrint('HealthConnect sync error: $e');
    }
  }

  void _computeCalorieHistory(List<Meal> meals, List<Workout> workouts) {
    final Map<String, double> eatenByDay = {};
    final Map<String, double> burnedByDay = {};

    for (final meal in meals) {
      final key = '${meal.dateTime.year}-${meal.dateTime.month.toString().padLeft(2, '0')}-${meal.dateTime.day.toString().padLeft(2, '0')}';
      eatenByDay[key] = (eatenByDay[key] ?? 0) + meal.calories;
    }

    for (final workout in workouts) {
      final key = '${workout.startTime.year}-${workout.startTime.month.toString().padLeft(2, '0')}-${workout.startTime.day.toString().padLeft(2, '0')}';
      burnedByDay[key] = (burnedByDay[key] ?? 0) + workout.caloriesBurned;
    }

    final history = <Map<String, dynamic>>[];
    final now = DateTime.now();
    for (int i = 29; i >= 0; i--) {
      final date = now.subtract(Duration(days: i));
      final key = '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';
      history.add({
        'date': date,
        'eaten': eatenByDay[key] ?? 0.0,
        'burned': burnedByDay[key] ?? 0.0,
      });
    }

    setState(() => _calorieHistory = history);
  }

  List<Map<String, dynamic>> _getSevenDayCalorieData(
    NutritionProvider nutrition,
    WorkoutProvider workout,
  ) {
    final List<Map<String, dynamic>> result = [];
    final now = DateTime.now();

    final weeklyCalories = nutrition.weeklyCalories;

    final workoutsByDate = <String, double>{};
    for (final w in workout.workouts) {
      if (w.endTime == null) continue;
      final dateKey = '${w.endTime!.year}-${w.endTime!.month.toString().padLeft(2, '0')}-${w.endTime!.day.toString().padLeft(2, '0')}';
      workoutsByDate[dateKey] = (workoutsByDate[dateKey] ?? 0) + w.caloriesBurned;
    }

    for (int i = 6; i >= 0; i--) {
      final date = now.subtract(Duration(days: i));
      final key = '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';
      final eaten = weeklyCalories[key] ?? 0;
      final burned = workoutsByDate[key] ?? 0;
      result.add({
        'date': date,
        'eaten': eaten,
        'burned': burned,
        'day': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][date.weekday - 1],
      });
    }
    return result;
  }

  Widget _buildSevenDayChart(List<Map<String, dynamic>> data) {
    if (data.isEmpty) return const SizedBox.shrink();

    final maxVal = data.fold<double>(
      0,
      (max, entry) => max > (entry['eaten'] as double) ? max : (entry['eaten'] as double),
    );
    final maxBurned = data.fold<double>(
      0,
      (max, entry) => max > (entry['burned'] as double) ? max : (entry['burned'] as double),
    );
    final overallMax = maxVal > maxBurned ? maxVal : maxBurned;

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              '7-Day Calorie History',
              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
            ),
            const SizedBox(height: 12),
            SizedBox(
              height: 200,
              child: BarChart(
                BarChartData(
                  gridData: const FlGridData(show: false),
                  titlesData: FlTitlesData(
                    leftTitles: AxisTitles(
                      sideTitles: SideTitles(
                        showTitles: true,
                        reservedSize: 40,
                        getTitlesWidget: (value, meta) => Text(
                          '${value.toInt()}',
                          style: const TextStyle(fontSize: 10),
                        ),
                      ),
                    ),
                    bottomTitles: AxisTitles(
                      sideTitles: SideTitles(
                        showTitles: true,
                        getTitlesWidget: (value, meta) {
                          final idx = value.toInt();
                          if (idx >= 0 && idx < data.length) {
                            return Text(
                              data[idx]['day'] as String,
                              style: const TextStyle(fontSize: 10),
                            );
                          }
                          return const Text('');
                        },
                      ),
                    ),
                    rightTitles: const AxisTitles(sideTitles: SideTitles(showTitles: false)),
                    topTitles: const AxisTitles(sideTitles: SideTitles(showTitles: false)),
                  ),
                  borderData: FlBorderData(show: false),
                  barGroups: data.asMap().entries.map((entry) {
                    final idx = entry.key;
                    final item = entry.value;
                    final eaten = item['eaten'] as double;
                    final burned = item['burned'] as double;
                    return BarChartGroupData(
                      x: idx,
                      barRods: [
                        BarChartRodData(
                          toY: eaten,
                          color: AppTheme.warningColor,
                          width: 12,
                          borderRadius: BorderRadius.circular(4),
                        ),
                        BarChartRodData(
                          toY: burned,
                          color: AppTheme.primaryColor,
                          width: 12,
                          borderRadius: BorderRadius.circular(4),
                        ),
                      ],
                      barsSpace: 4,
                    );
                  }).toList(),
                  minY: 0,
                  maxY: overallMax * 1.2,
                  barTouchData: BarTouchData(
                    touchTooltipData: BarTouchTooltipData(
                      getTooltipItem: (group, groupIndex, rod, rodIndex) {
                        final label = rodIndex == 0 ? 'Eaten' : 'Burned';
                        return BarTooltipItem(
                          '$label: ${rod.toY.toStringAsFixed(0)} kcal',
                          const TextStyle(color: Colors.white, fontSize: 12),
                        );
                      },
                    ),
                  ),
                ),
              ),
            ),
            const SizedBox(height: 8),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                _legendItem('Eaten', AppTheme.warningColor),
                const SizedBox(width: 16),
                _legendItem('Burned', AppTheme.primaryColor),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _legendItem(String label, Color color) {
    return Row(
      children: [
        Container(
          width: 12,
          height: 12,
          decoration: BoxDecoration(
            color: color,
            borderRadius: BorderRadius.circular(2),
          ),
        ),
        const SizedBox(width: 4),
        Text(
          label,
          style: const TextStyle(fontSize: 12, color: AppTheme.textSecondary),
        ),
      ],
    );
  }

  Future<void> _loadReportMeals(NutritionProvider nutrition, String userId) async {
    final now = DateTime.now();
    DateTime startDate;
    switch (_reportPeriod) {
      case 'This Week':
        startDate = now.subtract(Duration(days: now.weekday - 1));
        break;
      case 'This Month':
        startDate = DateTime(now.year, now.month, 1);
        break;
      case 'All Time':
        startDate = DateTime(2000, 1, 1);
        break;
      default:
        startDate = now.subtract(const Duration(days: 7));
    }
    await nutrition.loadMealsForDateRange(userId, startDate, now);
    _reportMeals = nutrition.dateRangeMeals;
  }

  List<WeightEntry> _getFilteredWeights() {
    final now = DateTime.now();
    List<WeightEntry> filtered = _weightHistory.where((e) {
      switch (_weightFilter) {
        case '1M':
          return e.date.isAfter(now.subtract(const Duration(days: 30)));
        case '6M':
          return e.date.isAfter(now.subtract(const Duration(days: 180)));
        case '1Y':
          return e.date.isAfter(now.subtract(const Duration(days: 365)));
        default:
          return true;
      }
    }).toList();
    filtered.sort((a, b) => a.date.compareTo(b.date));
    return filtered;
  }

  Widget _buildWeightProgressCard() {
    final filtered = _getFilteredWeights();
    if (filtered.isEmpty) {
      return Card(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            children: [
              const Text('Weight Progress',
                  style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
              const SizedBox(height: 12),
              const Text('No weight entries yet.',
                  style: TextStyle(color: AppTheme.textSecondary)),
              const SizedBox(height: 8),
              ElevatedButton.icon(
                onPressed: () => Navigator.pushNamed(context, '/nutrition'),
                icon: const Icon(Icons.add),
                label: const Text('Log Weight'),
              ),
            ],
          ),
        ),
      );
    }

    final minWeight =
        filtered.map((e) => e.weight).reduce((a, b) => a < b ? a : b);
    final maxWeight =
        filtered.map((e) => e.weight).reduce((a, b) => a > b ? a : b);
    final range = maxWeight - minWeight;
    final yMin = (minWeight - range * 0.1).clamp(0.0, minWeight);
    final yMax = maxWeight + range * 0.1;

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Text('Weight Progress',
                    style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                Row(
                  children: ['All', '1M', '6M', '1Y'].map((filter) {
                    return Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 4),
                      child: ChoiceChip(
                        label: Text(filter),
                        selected: _weightFilter == filter,
                        onSelected: (_) =>
                            setState(() => _weightFilter = filter),
                        selectedColor: AppTheme.primaryColor,
                        labelStyle: TextStyle(
                          color: _weightFilter == filter
                              ? Colors.white
                              : AppTheme.textSecondary,
                          fontSize: 12,
                        ),
                      ),
                    );
                  }).toList(),
                ),
              ],
            ),
            const SizedBox(height: 12),
            SizedBox(
              height: 150,
              child: LineChart(
                LineChartData(
                  gridData: FlGridData(
                    show: true,
                    drawVerticalLine: false,
                    horizontalInterval: (range / 5).clamp(1.0, 10.0),
                    getDrawingHorizontalLine: (value) => FlLine(
                      color: Colors.grey.withValues(alpha: 0.2),
                      strokeWidth: 1,
                    ),
                  ),
                  titlesData: FlTitlesData(
                    leftTitles: AxisTitles(
                      sideTitles: SideTitles(
                        showTitles: true,
                        reservedSize: 40,
                        getTitlesWidget: (value, meta) => Text(
                          '${value.toStringAsFixed(1)}',
                          style: const TextStyle(fontSize: 10),
                        ),
                      ),
                    ),
                    bottomTitles: AxisTitles(
                      sideTitles: SideTitles(
                        showTitles: true,
                        getTitlesWidget: (value, meta) {
                          final idx = value.toInt();
                          if (idx >= 0 && idx < filtered.length) {
                            final d = filtered[idx].date;
                            return Text(
                              '${d.day}/${d.month}',
                              style: const TextStyle(fontSize: 10),
                            );
                          }
                          return const Text('');
                        },
                      ),
                    ),
                    rightTitles: const AxisTitles(
                        sideTitles: SideTitles(showTitles: false)),
                    topTitles: const AxisTitles(
                        sideTitles: SideTitles(showTitles: false)),
                  ),
                  borderData: FlBorderData(show: false),
                  minY: yMin,
                  maxY: yMax,
                  lineBarsData: [
                    LineChartBarData(
                      spots: filtered.asMap().entries.map((e) {
                        return FlSpot(e.key.toDouble(), e.value.weight);
                      }).toList(),
                      isCurved: true,
                      color: AppTheme.primaryColor,
                      barWidth: 3,
                      isStrokeCapRound: true,
                      dotData: const FlDotData(show: true),
                      belowBarData: BarAreaData(
                        show: true,
                        color: AppTheme.primaryColor.withValues(alpha: 0.1),
                      ),
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 12),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: [
                _statItem('Current',
                    '${filtered.last.weight.toStringAsFixed(1)} kg',
                    AppTheme.primaryColor),
                _statItem('Lowest',
                    '${minWeight.toStringAsFixed(1)} kg',
                    AppTheme.successColor),
                _statItem('Highest',
                    '${maxWeight.toStringAsFixed(1)} kg',
                    AppTheme.warningColor),
              ],
            ),
            if (filtered.length > 3) ...[
              const Divider(),
              const SizedBox(height: 4),
              const Text('Recent Entries',
                  style: TextStyle(fontWeight: FontWeight.w600, fontSize: 14)),
              const SizedBox(height: 8),
              ...filtered.reversed.take(3).map((entry) {
                final dateStr = DateFormat('d MMM yyyy').format(entry.date);
                return Padding(
                  padding: const EdgeInsets.symmetric(vertical: 2),
                  child: Row(
                    children: [
                      Text(dateStr,
                          style: const TextStyle(fontSize: 13)),
                      const Spacer(),
                      Text('${entry.weight.toStringAsFixed(1)} kg',
                          style: const TextStyle(fontWeight: FontWeight.bold)),
                    ],
                  ),
                );
              }),
            ],
          ],
        ),
      ),
    );
  }

  // ─── REPORTS CARD (separate, same as image) ──────────────────
  Widget _buildReportsCard() {
    final nutrition = context.read<NutritionProvider>();
    final workout = context.read<WorkoutProvider>();
    final meals = _reportMeals;

    final totalCalories = meals.fold<double>(0, (s, m) => s + m.calories);
    final totalProtein = meals.fold<double>(0, (s, m) => s + m.protein);
    final totalCarbs = meals.fold<double>(0, (s, m) => s + m.carbs);
    final totalFat = meals.fold<double>(0, (s, m) => s + m.fat);
    final totalFiber = meals.fold<double>(0, (s, m) => s + m.fiber);

    final now = DateTime.now();
    DateTime startDate;
    switch (_reportPeriod) {
      case 'This Week':
        startDate = now.subtract(Duration(days: now.weekday - 1));
        break;
      case 'This Month':
        startDate = DateTime(now.year, now.month, 1);
        break;
      case 'All Time':
        startDate = DateTime(2000, 1, 1);
        break;
      default:
        startDate = now.subtract(const Duration(days: 7));
    }
    final workoutsInRange = workout.workouts
        .where((w) => w.endTime != null && w.endTime!.isAfter(startDate))
        .toList();
    final totalBurned = workoutsInRange.fold<double>(0, (s, w) => s + w.caloriesBurned);

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Text(
                  'Reports',
                  style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                ),
                DropdownButton<String>(
                  value: _reportPeriod,
                  items: ['This Week', 'This Month', 'All Time']
                      .map((period) => DropdownMenuItem(
                          value: period, child: Text(period)))
                      .toList(),
                  onChanged: (v) async {
                    setState(() => _reportPeriod = v!);
                    final auth = context.read<AuthProvider>();
                    if (auth.user != null) {
                      await _loadReportMeals(
                          context.read<NutritionProvider>(), auth.user!.uid);
                      setState(() {});
                    }
                  },
                ),
              ],
            ),
            const SizedBox(height: 12),
            // ── Using Wrap to prevent overflow ──
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                _reportChip('Calories', '${totalCalories.toInt()} kcal', Colors.orange),
                _reportChip('Protein', '${totalProtein.toStringAsFixed(0)}g', AppTheme.accentColor),
                _reportChip('Carbs', '${totalCarbs.toStringAsFixed(0)}g', AppTheme.successColor),
                _reportChip('Fat', '${totalFat.toStringAsFixed(0)}g', AppTheme.secondaryColor),
                if (totalFiber > 0)
                  _reportChip('Fiber', '${totalFiber.toStringAsFixed(0)}g', Colors.brown),
                _reportChip('Burned', '${totalBurned.toInt()} kcal', AppTheme.primaryColor),
              ],
            ),
          ],
        ),
      ),
    );
  }

  // ─── 30-DAY HISTORY CARD (separate) ──────────────────────────
  Widget _buildHistorySummary() {
    if (_calorieHistory.isEmpty) return const SizedBox.shrink();

    final totalEaten = _calorieHistory.fold<double>(0, (sum, d) => sum + (d['eaten'] as double));
    final totalBurned = _calorieHistory.fold<double>(0, (sum, d) => sum + (d['burned'] as double));
    final dailyAvg = _calorieHistory.isEmpty ? 0 : totalEaten / _calorieHistory.length;
    final netBalance = totalEaten - totalBurned;

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(10),
                  decoration: BoxDecoration(
                    color: AppTheme.primaryColor.withValues(alpha: 0.1),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: const Icon(Icons.history, color: AppTheme.primaryColor, size: 24),
                ),
                const SizedBox(width: 14),
                const Text(
                  '30-Day History',
                  style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                ),
              ],
            ),
            const SizedBox(height: 16),
            Row(
              children: [
                Expanded(
                  child: _statBox(
                    'Total Eaten',
                    '${totalEaten.toStringAsFixed(0)} kcal',
                    AppTheme.accentColor,
                    Icons.restaurant,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: _statBox(
                    'Total Burned',
                    '${totalBurned.toStringAsFixed(0)} kcal',
                    AppTheme.warningColor,
                    Icons.local_fire_department,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            Row(
              children: [
                Expanded(
                  child: _statBox(
                    'Daily Avg',
                    '${dailyAvg.toStringAsFixed(0)} kcal',
                    AppTheme.primaryColor,
                    Icons.bar_chart,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: _statBox(
                    'Net Balance',
                    '${netBalance.toStringAsFixed(0)} kcal',
                    netBalance > 0 ? AppTheme.warningColor : AppTheme.successColor,
                    netBalance > 0 ? Icons.arrow_upward : Icons.arrow_downward,
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  // ─── Helper widgets for Reports & History ────────────────────

  Widget _reportChip(String label, String value, Color color) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.08),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: color.withValues(alpha: 0.2)),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(label, style: TextStyle(fontSize: 11, color: color)),
          const SizedBox(width: 4),
          Text(value,
              style: TextStyle(
                  fontSize: 11,
                  fontWeight: FontWeight.bold,
                  color: color)),
        ],
      ),
    );
  }

  Widget _statBox(String label, String value, Color color, IconData icon) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.08),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(icon, size: 14, color: color),
              const SizedBox(width: 6),
              Text(
                label,
                style: TextStyle(fontSize: 11, color: AppTheme.textSecondary),
                overflow: TextOverflow.ellipsis,
                maxLines: 1,
              ),
            ],
          ),
          const SizedBox(height: 6),
          Text(
            value,
            style: TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.bold,
              color: color,
            ),
            overflow: TextOverflow.ellipsis,
            maxLines: 1,
          ),
        ],
      ),
    );
  }

  Widget _statItem(String label, String value, Color color) {
    return Column(
      children: [
        Text(value,
            style: TextStyle(
                fontWeight: FontWeight.bold, fontSize: 16, color: color)),
        Text(label,
            style:
                const TextStyle(fontSize: 11, color: AppTheme.textSecondary)),
      ],
    );
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.paused ||
        state == AppLifecycleState.detached) {
      _saveTodaySteps();
    }
  }

  // ── Build ──

  @override
  Widget build(BuildContext context) {
    final user = context.select((AuthProvider p) => p.user);
    final sleep = context.select((SleepProvider p) => p.lastNightSleep);
    final calories = context.select(
      (NutritionProvider p) => p.totalCaloriesToday,
    );
    final heartRate = context.select((HealthProvider p) => p.currentHeartRate);
    final hrHistory = context.select((HealthProvider p) => p.heartRateHistory);
    final stepsToday = context.select((HealthProvider p) => p.stepsToday);
    final caloriesBurned = context.select(
      (WorkoutProvider p) => p.todayCaloriesBurned,
    );
    final selectedPlan = context.select((PlanningProvider p) => p.selectedPlan);
    final nutrition = context.read<NutritionProvider>();
    final workout = context.read<WorkoutProvider>();

    return QuickTour(
      key: _quickTourKey,
      steps: widget.tourSteps,
      onFinished: () async {
        final auth = context.read<AuthProvider>();
        final prefs = await SharedPreferences.getInstance();
        await prefs.setBool('quick_tour_done', true);
        if (auth.user != null) {
          final updated = auth.user!.copyWith(hasSeenQuickTour: true);
          await auth.updateProfile(updated);
        }
      },
      onSkipped: () async {
        final auth = context.read<AuthProvider>();
        final prefs = await SharedPreferences.getInstance();
        await prefs.setBool('quick_tour_done', true);
        if (auth.user != null) {
          final updated = auth.user!.copyWith(hasSeenQuickTour: true);
          await auth.updateProfile(updated);
        }
      },
      child: Scaffold(
        appBar: null,
        body: RefreshIndicator(
          onRefresh: _loadData,
          child: SingleChildScrollView(
            physics: const AlwaysScrollableScrollPhysics(),
            padding: const EdgeInsets.all(16),
            child: ShimmerLoading(
              isLoading: _isDashboardLoading,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // ── Header ──
                  Row(
                    children: [
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Hello, ${user?.displayName ?? 'User'}',
                              style: const TextStyle(
                                fontSize: 24,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ],
                        ),
                      ),
                      if (_showTourPrompt)
                        IconButton(
                          icon: const Icon(Icons.help_outline),
                          tooltip: 'Quick Tour',
                          onPressed: () => _quickTourKey.currentState?.start(),
                        ),
                      IconButton(
                        key: widget.aiChatKey,
                        icon: const Icon(Icons.auto_awesome),
                        tooltip: 'AI Assistant',
                        onPressed: () =>
                            Navigator.pushNamed(context, '/ai-chat'),
                      ),
                    ],
                  ),
                  const SizedBox(height: 16),

                  // ── Tour Prompt ──
                  if (_showTourPrompt) _buildTourPrompt(),

                  // ── Today's Overview ──
                  const Text(
                    'Today\'s Overview',
                    style: TextStyle(fontSize: 20, fontWeight: FontWeight.w600),
                  ),
                  const SizedBox(height: 16),

                  // Row 1: Steps + Heart Rate
                  Row(
                    children: [
                      Expanded(
                        child: _StatusCard(
                          icon: Icons.directions_walk,
                          label: 'Steps',
                          value: stepsToday.toString(),
                          unit: 'steps',
                          color: Colors.green,
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: _StatusCard(
                          icon: Icons.favorite,
                          label: 'Heart Rate',
                          value: heartRate == 0 ? '--' : '$heartRate',
                          unit: 'bpm',
                          color: AppTheme.accentColor,
                          child: hrHistory.isNotEmpty
                              ? Padding(
                                  padding: const EdgeInsets.only(top: 8),
                                  child: _HrSparkline(
                                    data: hrHistory,
                                    lineColor: AppTheme.accentColor,
                                  ),
                                )
                              : null,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),

                  // Row 2: Calories + Sleep
                  Row(
                    children: [
                      Expanded(
                        child: _CaloriesCard(
                          eatenCalories: calories,
                          burnedCalories: caloriesBurned,
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: _StatusCard(
                          icon: Icons.bedtime,
                          label: 'Sleep',
                          value: sleep != null
                              ? sleep.hoursSlept.toStringAsFixed(1)
                              : '--',
                          unit: 'hours',
                          color: AppTheme.secondaryColor,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 16),

                  // ── Run Tracker ──
                  const _RunTrackerCard(),
                  const SizedBox(height: 16),

                  // ── Map Preview ──
                  const MapPreviewCard(),
                  const SizedBox(height: 16),

                  // ── Active Plan ──
                  _buildPlanningSection(selectedPlan),
                  const SizedBox(height: 16),

                  // ── 7-Day Calorie Chart ──
                  if (!_isDashboardLoading)
                    _buildSevenDayChart(_getSevenDayCalorieData(nutrition, workout)),
                  const SizedBox(height: 16),

                  // ── Weight Progress ──
                  if (!_isDashboardLoading)
                    _buildWeightProgressCard(),
                  const SizedBox(height: 16),

                  // ── Reports (separate) ──
                  if (!_isDashboardLoading)
                    _buildReportsCard(),
                  const SizedBox(height: 16),

                  // ── 30-Day History (separate) ──
                  _buildHistorySummary(),
                  const SizedBox(height: 16),

                  // ── News Carousel ──
                  const NewsCarousel(),
                  const SizedBox(height: 16),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  // ── Build: Tour Prompt ──

  Widget _buildTourPrompt() {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Container(
        decoration: BoxDecoration(
          gradient: const LinearGradient(
            colors: [Color(0xFF6366F1), Color(0xFF818CF8)],
          ),
          borderRadius: BorderRadius.circular(16),
        ),
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Row(
            children: [
              Container(
                width: 44,
                height: 44,
                decoration: BoxDecoration(
                  color: Colors.white.withValues(alpha: 0.2),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: const Icon(Icons.explore, color: Colors.white, size: 24),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'New Here? Take a Tour',
                      style: TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.bold,
                        fontSize: 15,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      'Learn every feature step by step',
                      style: TextStyle(
                        color: Colors.white.withValues(alpha: 0.8),
                        fontSize: 12,
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(width: 8),
              TextButton(
                onPressed: () => _quickTourKey.currentState?.start(),
                style: TextButton.styleFrom(
                  backgroundColor: Colors.white,
                  foregroundColor: const Color(0xFF6366F1),
                  padding: const EdgeInsets.symmetric(
                    horizontal: 20,
                    vertical: 10,
                  ),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                ),
                child: const Text(
                  'Start',
                  style: TextStyle(fontWeight: FontWeight.w600),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  // ── Build: Planning Section ──

  Widget _buildPlanningSection(FitnessPlan? plan) {
    if (plan == null) {
      return Card(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Row(
            children: [
              Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: AppTheme.primaryColor.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: const Icon(
                  Icons.auto_awesome,
                  color: AppTheme.primaryColor,
                  size: 24,
                ),
              ),
              const SizedBox(width: 14),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'AI Planning',
                      style: TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 16,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      'Tap to generate a personalized plan',
                      style: TextStyle(
                        color: AppTheme.textSecondary,
                        fontSize: 13,
                      ),
                    ),
                  ],
                ),
              ),
              IconButton(
                icon: const Icon(
                  Icons.arrow_forward,
                  color: AppTheme.primaryColor,
                ),
                onPressed: () => Navigator.pushNamed(context, '/planning'),
              ),
            ],
          ),
        ),
      );
    }

    final dayNames = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
    final todayName = dayNames[DateTime.now().weekday - 1];
    final todayWorkout = plan.weeklyWorkouts.where((w) => w.day == todayName).firstOrNull;

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(10),
                  decoration: BoxDecoration(
                    color: AppTheme.successColor.withValues(alpha: 0.1),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: const Icon(
                    Icons.fitness_center,
                    color: AppTheme.successColor,
                    size: 24,
                  ),
                ),
                const SizedBox(width: 14),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text(
                        'Active Plan',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                      const SizedBox(height: 2),
                      Text(
                        plan.title,
                        style: TextStyle(
                          color: AppTheme.textSecondary,
                          fontSize: 13,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 16),
            Row(
              children: [
                _planStat(Icons.local_fire_department, '${plan.dailyCalories}', 'kcal today'),
                const SizedBox(width: 24),
                _planStat(
                  Icons.fitness_center,
                  todayWorkout?.focus ?? 'Rest Day',
                  todayWorkout != null ? '${todayWorkout.durationMinutes} min' : '',
                ),
              ],
            ),
            const SizedBox(height: 16),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: () => Navigator.pushNamed(context, '/workout'),
                icon: const Icon(Icons.play_arrow, size: 18),
                label: const Text('Start Workout'),
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 12),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _planStat(IconData icon, String label, String sub) {
    return Row(
      children: [
        Icon(icon, size: 18, color: AppTheme.primaryColor),
        const SizedBox(width: 6),
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              label,
              style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 15),
            ),
            if (sub.isNotEmpty)
              Text(
                sub,
                style: TextStyle(fontSize: 11, color: AppTheme.textSecondary),
              ),
          ],
        ),
      ],
    );
  }
}

// ─── Card Widgets ──────────────────────────────────────────────

class _StatusCard extends StatelessWidget {
  final IconData icon;
  final String label;
  final String value;
  final String unit;
  final Color color;
  final Widget? child;
  final VoidCallback? onTap;

  const _StatusCard({
    required this.icon,
    required this.label,
    required this.value,
    required this.unit,
    required this.color,
    this.child,
    this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return Semantics(
      label: '$label: $value $unit',
      child: Card(
        child: InkWell(
          onTap: onTap,
          borderRadius: BorderRadius.circular(16),
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: color.withValues(alpha: 0.1),
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: Icon(icon, color: color, size: 20),
                ),
                const SizedBox(height: 10),
                Text(
                  label,
                  style: Theme.of(context).textTheme.bodySmall?.copyWith(
                    color: AppTheme.textSecondary,
                  ),
                ),
                const SizedBox(height: 4),
                Row(
                  crossAxisAlignment: CrossAxisAlignment.end,
                  children: [
                    Flexible(
                      child: Text(
                        value,
                        style: Theme.of(context).textTheme.headlineSmall
                            ?.copyWith(fontWeight: FontWeight.bold),
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                    if (unit.isNotEmpty)
                      Padding(
                        padding: const EdgeInsets.only(left: 4, bottom: 4),
                        child: Text(
                          unit,
                          style: Theme.of(context).textTheme.bodySmall
                              ?.copyWith(color: AppTheme.textSecondary),
                        ),
                      ),
                  ],
                ),
                if (child != null) ...[const SizedBox(height: 4), child!],
              ],
            ),
          ),
        ),
      ),
    );
  }
}

// ─── Calories Card ─────────────────────────────────────────────
// ─── Calories Card ─────────────────────────────────────────────
class _CaloriesCard extends StatelessWidget {
  final double eatenCalories;
  final double burnedCalories;

  const _CaloriesCard({
    required this.eatenCalories,
    required this.burnedCalories,
  });

  @override
  Widget build(BuildContext context) {
    final net = eatenCalories - burnedCalories;
    final inDeficit = net <= 0;

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: AppTheme.warningColor.withValues(alpha: 0.1),
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: const Icon(
                    Icons.local_fire_department,
                    color: AppTheme.warningColor,
                    size: 20,
                  ),
                ),
                const SizedBox(width: 12),
                const Flexible(
                  child: Text(
                    'Today\'s Calories',
                    style: TextStyle(
                      fontSize: 14,
                      fontWeight: FontWeight.w600,
                      color: AppTheme.textSecondary,
                    ),
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  'Net Balance',
                  style: TextStyle(fontSize: 13, color: AppTheme.textSecondary),
                ),
                const SizedBox(height: 4),
                FittedBox(
                  fit: BoxFit.scaleDown,
                  child: Row(
                    children: [
                      Text(
                        '${net.toStringAsFixed(0)} kcal',
                        style: TextStyle(
                          fontSize: 20,
                          fontWeight: FontWeight.bold,
                          color: inDeficit ? AppTheme.successColor : AppTheme.warningColor,
                        ),
                      ),
                      const SizedBox(width: 6),
                      Icon(
                        inDeficit ? Icons.arrow_downward : Icons.arrow_upward,
                        size: 18,
                        color: inDeficit ? AppTheme.successColor : AppTheme.warningColor,
                      ),
                      const SizedBox(width: 4),
                      Text(
                        inDeficit ? 'deficit' : 'surplus',
                        style: TextStyle(
                          fontSize: 12,
                          color: inDeficit ? AppTheme.successColor : AppTheme.warningColor,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
            if (eatenCalories > 0 || burnedCalories > 0) ...[
              const SizedBox(height: 12),
              Wrap(
                spacing: 8,
                runSpacing: 4,
                children: [
                  Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      _calorieDot(AppTheme.accentColor),
                      const SizedBox(width: 4),
                      Text(
                        'Eaten ${eatenCalories.toStringAsFixed(0)}',
                        style: const TextStyle(fontSize: 11, color: AppTheme.textSecondary),
                      ),
                    ],
                  ),
                  Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      _calorieDot(AppTheme.warningColor),
                      const SizedBox(width: 4),
                      Text(
                        'Burned ${burnedCalories.toStringAsFixed(0)}',
                        style: const TextStyle(fontSize: 11, color: AppTheme.textSecondary),
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ],
        ),
      ),
    );
  }

  Widget _calorieDot(Color color) {
    return Container(
      width: 8,
      height: 8,
      decoration: BoxDecoration(color: color, shape: BoxShape.circle),
    );
  }
}


// ─── HR Sparkline ─────────────────────────────────────────────

class _HrSparkline extends StatelessWidget {
  final List<int> data;
  final Color lineColor;

  const _HrSparkline({required this.data, required this.lineColor});

  @override
  Widget build(BuildContext context) {
    if (data.length < 2) return const SizedBox.shrink();
    return SizedBox(
      height: 32,
      child: CustomPaint(
        painter: _SparklinePainter(data: data, color: lineColor),
        size: const Size(double.infinity, 32),
      ),
    );
  }
}

class _SparklinePainter extends CustomPainter {
  final List<int> data;
  final Color color;

  _SparklinePainter({required this.data, required this.color});

  @override
  void paint(Canvas canvas, Size size) {
    if (data.length < 2) return;

    final paint = Paint()
      ..color = color
      ..strokeWidth = 2
      ..style = PaintingStyle.stroke
      ..strokeCap = StrokeCap.round
      ..strokeJoin = StrokeJoin.round;

    final fillPaint = Paint()
      ..shader = LinearGradient(
        begin: Alignment.topCenter,
        end: Alignment.bottomCenter,
        colors: [color.withValues(alpha: 0.3), color.withValues(alpha: 0.0)],
      ).createShader(Rect.fromLTWH(0, 0, size.width, size.height))
      ..style = PaintingStyle.fill;

    final path = Path();
    final fillPath = Path();

    final step = size.width / (data.length - 1);
    final min = data.reduce((a, b) => a < b ? a : b).toDouble();
    final max = data.reduce((a, b) => a > b ? a : b).toDouble();
    final range = max - min > 0 ? max - min : 60.0;
    final padding = 2.0;

    for (int i = 0; i < data.length; i++) {
      final x = i * step;
      final y =
          size.height -
          ((data[i] - min) / range) * (size.height - padding * 2) -
          padding;
      if (i == 0) {
        path.moveTo(x, y);
        fillPath.moveTo(x, size.height);
        fillPath.lineTo(x, y);
      } else {
        path.lineTo(x, y);
        fillPath.lineTo(x, y);
      }
    }

    fillPath.lineTo((data.length - 1) * step, size.height);
    fillPath.close();

    canvas.drawPath(fillPath, fillPaint);
    canvas.drawPath(path, paint);
  }

  @override
  bool shouldRepaint(covariant _SparklinePainter old) =>
      data != old.data || color != old.color;
}

// ── Run Tracker Card ──
class _RunTrackerCard extends StatelessWidget {
  const _RunTrackerCard();

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(10),
              decoration: BoxDecoration(
                color: Colors.green.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(12),
              ),
              child: const Icon(
                Icons.directions_run,
                color: Colors.green,
                size: 24,
              ),
            ),
            const SizedBox(width: 14),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text(
                    'Run & Walk Tracker',
                    style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                  ),
                  const SizedBox(height: 2),
                  Text(
                    'Track your runs and walks with distance, time & calories',
                    style: TextStyle(color: AppTheme.textSecondary, fontSize: 13),
                  ),
                ],
              ),
            ),
            ElevatedButton.icon(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (_) => const RunTrackingScreen()),
                );
              },
              icon: const Icon(Icons.play_arrow, size: 18),
              label: const Text('Start'),
              style: ElevatedButton.styleFrom(
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}